pipeline {
    agent any

    stages {
        stage('Unit Tests-Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                    
                }
            }
            steps {
             dir ('bugtarker-backend') {
                sh 'go test -v ./...'
            }
        }
    }
}