pipeline {
    agent any

    environment {
        GOCACHE = '/tmp/go-build'
        GOTMPDIR = '/tmp/go-tmp'
        HOME = '/tmp'
    }

    stages {
        stage('Unit Tests-Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh '''
                        mkdir -p ${WORKSPACE}/.gopath/pkg/mod ${WORKSPACE}/.gocache ${GOTMPDIR}
                        export GOPATH=${WORKSPACE}/.gopath
                        export GOMODCACHE=${GOPATH}/pkg/mod
                        export GOCACHE=${WORKSPACE}/.gocache
                        go test -v ./... > go-test-output.log 2>&1
                        cat go-test-output.log | go-junit-report > ${WORKSPACE}/bugtracker-backend/test-results.xml
                        # Generate coverage report
                        go test -coverprofile=coverage.out -covermode=atomic ./...
                        go tool cover -html=coverage.out -o coverage.html

                        mkdir -p reports
                        mv coverage.html reports/

                    '''
                    
                }
            }
            post {
                always {
                    junit 'bugtracker-backend/test-results.xml'
                    publishHTML(target: [
                    
                        reportDir: 'bugtracker-backend/reports',
                        reportFiles: 'coverage.html',
                        reportName: 'BackendCoverage Report'
                    ])
                }
            }
        }
        stage('Unit Tests-Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                    args '--user root:root -e HOME=/tmp'
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm install --no-audit --no-fund
                        npm test -- --watch=false
                        mkdir -p reports
                        mv coverage reports/
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                    publishHTML target: [
                        reportDir: 'bugtracker-frontend/reports/coverage',
                        reportFiles: 'index.html',
                        reportName: 'Frontend Coverage Report'
                    ]
                }
            }
        }
    }
}
